application: lunch--mates
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

# Task queues & scheduled tasks
- url: /tasks/.*
  script: main.tasks
  login: admin

# Frontends
- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.1"
